[package]
name = "anything-pdk-test-runner"
version = "0.0.1"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[build]
target = "wasm32-unknown-unknown"

[dependencies]
extism-pdk = "1.1.0"
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"
xtp-test = "0.0.1-rc7"
