[package]
name = "anything-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = { workspace = true }
tempfile = { workspace = true }

anything-core = { path = "../anything-core", version = "0.1.0" }
async-trait = { workspace = true }
tokio = { workspace = true }

temp-dir = "0.1.11"
sqlx = { version = "0.7.1", features = [
  "sqlite",
  "macros",
  "any",
  "runtime-tokio",
] }

# Tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
