[phases.setup]
nixPkgs = [
  "pkg-config",
  "openssl.dev",
  "gcc",
  "curl",
  "git",
  "python3",
  "nodejs-18_x",
]

[phases.install]
cmds = [
  "ln -sf /usr/bin/python3 /usr/bin/python"
]

[phases.build]
cmds = [
  "cargo build --release"
]

[start]
cmd = "./target/release/anything-server"

[variables]
RUSTY_V8_MIRROR = "https://github.com/denoland/rusty_v8/releases/download"
V8_FROM_SOURCE = "1"
RUST_BACKTRACE = "1"
OPENSSL_DIR = "/nix/store"
OPENSSL_LIB_DIR = "/nix/store"
OPENSSL_INCLUDE_DIR = "/nix/store"